service: aws-sns-on-discord
frameworkVersion: "3"
useDotenv: true
plugins:
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  memorySize: 128
functions:
  discord-notify:
    handler: index.notify
    events:
      - sns:
          topicName: CW_Alarm_Notify_Discord
